/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "cardContainer": string|undefined
  "cardHeader": string|undefined
  "cardInnerContainer": string|undefined
  "color300": string|undefined
  "color350": string|undefined
  "color400": string|undefined
  "color450": string|undefined
  "container": string|undefined
  "dot": string|undefined
  "firstEmpty": string|undefined
  "fourthEmpty": string|undefined
  "header": string|undefined
  "headerTitle": string|undefined
  "headerWrapper": string|undefined
  "itemContainer": string|undefined
  "itemText": string|undefined
  "itemsContainer": string|undefined
  "line": string|undefined
  "roadMapCardsContainer": string|undefined
  "roadmapCardContainer": string|undefined
  "secondEmpty": string|undefined
  "thirdEmpty": string|undefined
  "title": string|undefined
}
