/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "buttonText": string|undefined
  "contactCard": string|undefined
  "container": string|undefined
  "subtitle": string|undefined
}
