/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "cardsContainer": string|undefined
  "column": string|undefined
  "contactCard": string|undefined
  "contactHeader": string|undefined
  "imageContainer": string|undefined
  "partnerCardContainer": string|undefined
  "wrapper": string|undefined
}
