/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "container": string|undefined
  "firsLineFirstItem": string|undefined
  "firstLineContainer": string|undefined
  "firstLineSecondItem": string|undefined
  "lineContainer": string|undefined
  "secondLineContainer": string|undefined
  "secondLineItems": string|undefined
}
