/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "card": string|undefined
  "cardContainer": string|undefined
  "container": string|undefined
  "hexagonsImage": string|undefined
  "img": string|undefined
  "imgContainer": string|undefined
  "innerContainer": string|undefined
  "mdBody": string|undefined
  "mdHeader": string|undefined
  "newsImage": string|undefined
}
