/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "cardContainer": string|undefined
  "container": string|undefined
  "mdBody": string|undefined
  "mdHeader": string|undefined
}
