/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "black": string|undefined
  "container": string|undefined
  "paddinglg": string|undefined
  "paddingmd": string|undefined
  "paddingsm": string|undefined
  "paddingxl": string|undefined
  "paddingxxl": string|undefined
  "white": string|undefined
}
