/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "buttonTitle": string|undefined
  "container": string|undefined
  "formContainer": string|undefined
  "imageContainer": string|undefined
  "inputContainer": string|undefined
  "titleContainer": string|undefined
}
