/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "body1": string|undefined
  "body2": string|undefined
  "dark": string|undefined
  "headerContainer": string|undefined
  "light": string|undefined
  "root": string|undefined
  "screenContainer": string|undefined
  "title1": string|undefined
}
