/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "anime": string|undefined
  "buttonIcon": string|undefined
  "buttonText": string|undefined
  "container": string|undefined
  "mainButton": string|undefined
}
