/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "cardContainer": string|undefined
  "cardInnerContainer": string|undefined
  "container": string|undefined
  "header": string|undefined
  "headerTitle": string|undefined
  "line": string|undefined
  "roadMapCardsContainer": string|undefined
}
