/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "bgContainer": string|undefined
  "container": string|undefined
  "header": string|undefined
  "headerContainer": string|undefined
  "img": string|undefined
  "imgContainer": string|undefined
  "mask": string|undefined
}
