/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "aboutContainer": string|undefined
  "column": string|undefined
  "columnContainer": string|undefined
  "columnTitle": string|undefined
  "footer": string|undefined
  "linksContainer": string|undefined
  "logoContainer": string|undefined
}
