/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "cardsContainer": string|undefined
  "flex1": string|undefined
  "secondaryCardsContainer": string|undefined
}
