/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "container": string|undefined
  "imgContainer": string|undefined
  "md": string|undefined
  "sm": string|undefined
  "titleContainer": string|undefined
}
