/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "container": string|undefined
  "firstLine": string|undefined
  "item": string|undefined
  "secondLine": string|undefined
}
